name: .NET Core

on:
  push:
    branches: [ develop ]

jobs:
  develop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core 5.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore packages.
      run: dotnet restore
    - name: Build all projects.
      run: dotnet build --configuration Release --no-restore
    - name: Unittests.
      run: dotnet test
      working-directory: ./test/OsmSharp.IO.Binary.Test/
    - name: Functional tests.
      run: dotnet run -c release
      working-directory: ./test/OsmSharp.IO.Binary.Test.Functional/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/OsmSharp.IO.Binary/
    - name: Nuget push
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/osmsharp/index.json
      working-directory: ./src/